### Utility functions for taking input of samples

In [1]:
def input_data(n=None, dtype=float):
    data = []
    i = 0
    while True:
        if i==n: return data
        inp = input(f'Enter element {i+1}: ')
        if not inp and n is None: return data
        data.append(dtype(inp))
        i += 1

def input_table(r=None, c=None, dtype=float, ragged=False):
    print('Row 1:')
    row1 = input_data(c, dtype=dtype)
    table = [row1]
    c_new = c if ragged else len(row1)
    while True:
        try:
            if len(table)==r: return table
            print(f'Row {len(table)+1}:')
            row = input_data(c_new, dtype=dtype)
            if not row and r is None: return table
            table.append(row)
        except ValueError as e:
            if r is c is None: return table
            else: raise e

## 7a: Write a program to implement simple regression analysis.

In [2]:
import numpy as np

class SimpleRegression:
    def __init__(self, degree=1):
        self.deg = degree
    
    def fit(self, x, y):
        x, y = np.asarray(x), np.asarray(y)
        A, b = [], []
        for i in range(self.deg+1):
            A.append([np.sum(x**(i+j)) for j in range(self.deg+1)])
            b.append(np.sum((x**i)*y))
        
        self.coeffs = np.linalg.solve(A, b)
    
    def predict(self, x):
        return np.dot(np.transpose([x])**range(self.deg+1), self.coeffs)

In [3]:
linear_regressor = SimpleRegression(degree=1)
quad_regressor = SimpleRegression(degree=2)

In [4]:
x = input_data()
y = input_data(len(x))
to_pred = input_data()

linear_regressor.fit(x, y)
quad_regressor.fit(x, y)

In [5]:
print('x:', x)
print('y:', y)
print('Values to predict:', to_pred)

x: [0.2, 0.4, 0.6, 0.8, 1.0, 1.2]
y: [8.2, 8.4, 8.5, 8.6, 8.8, 8.7]
Values to predict: [1.5, 2.0]


In [6]:
linear_regressor.coeffs

array([8.15333333, 0.54285714])

In [7]:
linear_regressor.predict(to_pred)

array([8.96761905, 9.23904762])

In [9]:
quad_regressor.coeffs

array([ 7.97      ,  1.23035714, -0.49107143])

In [7]:
quad_regressor.predict(to_pred)

array([8.710625  , 8.46642857])

## 7b: Write a program to implement multiple regression analysis.

In [10]:
import numpy as np

class MultipleRegression:
    def fit(self, X, y):
        X, y = np.c_[np.ones(len(X)), X].T, np.asarray(y)
        A, b = [], []
        for i in range(len(X)):
            A.append([np.sum(X[i]*X[j]) for j in range(len(X))])
            b.append(np.sum(X[i]*y))
        
        self.coeffs = np.linalg.solve(A, b)
    
    def predict(self, X):
        return self.coeffs[0] + np.dot(X, self.coeffs[1:])

In [12]:
multi_regressor = MultipleRegression()

In [14]:
X = input_table()
y = input_data(len(X))
to_pred = input_table()

multi_regressor.fit(X, y)

Row 1:
Row 2:
Row 3:
Row 1:
Row 2:


In [15]:
print('X:', X)
print('y:', y)
print('Values to predict:', to_pred)

X: [[5.0, 3.0], [5.0, -3.0]]
y: [7.0, 1.0]
Values to predict: [[7.0, 9.0]]


In [16]:
multi_regressor.coeffs

array([-2.22044605e-16,  8.00000000e-01,  1.00000000e+00])

In [17]:
multi_regressor.predict(to_pred)

array([14.6])